server:
    port: 8096
jwt:
    auth:
        converter:
            resource-id: springboot-keycloak-client
            principal-attribute: preferred_username
spring:
    application:
        name: springboot-keycloak
    datasource:
        url: jdbc:postgresql://localhost:5432/tdcDb
        username: postgres
        password: postgres
        driverClassName=: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate.ddl-auto: validate
    servlet:
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 20MB
    jackson:
        default-property-inclusion: NON_NULL
    liquibase:
        change-log: db/db.changelog-master.xml
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8090/realms/SpringBootKeycloak
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
logging:
    level:
        org.springframework.security: DEBUG

it:
    ctinnovation:
        web:
            security:
                server:
                    cors:
                        enabled: true
                        allowed-origin:
                        - http://localhost:1841

cloud:
    aws:
        credentials:
            accessKey: AKIAZYQYWUM4J6TDMJLY
            secretKey: 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
        region:
            static: eu-central-1
            auto: false
        roles:
            in:
                producer:
                    key: dev.geo.drools.in.producer
                    role: arn:aws:iam::671140455224:role/dev.geo.drools.in.producer
                consumer:
                    key: dev.geo.drools.in.consumer
                    role: arn:aws:iam::671140455224:role/dev.geo.drools.in.consumer
            out:
                producer:
                    key: dev.geo.drools.out.producer
                    role: arn:aws:iam::671140455224:role/dev.geo.drools.out.producer
                consumer:
                    key: dev.geo.drools.out.consumer
                    role: arn:aws:iam::671140455224:role/dev.geo.drools.out.consumer

sqs:
    session: test
    queues:
        in:
            queue: dev-geo-drools-in.fifo
            url: https://sqs.eu-central-1.amazonaws.com/671140455224/dev-geo-drools-in.fifo
            waitTimeSeconds: 10
            maxNumberMessages: 10
        out:
            queue: dev-geo-drools-out.fifo
            url: https://sqs.eu-central-1.amazonaws.com/671140455224/dev-geo-drools-out.fifo

mqtt:
    url: tcp://test.mosquitto.org:1883
    clientId: TheatherDemoConf
    defaultTopic: fd875cf3-2865-4442-acf5-6b4c19d92a9a/demo
